spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.38.150:3306/spring-authorization-server-example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  level:
    root: info
    org.springframework.security.web.FilterChainProxy: trace # 过滤器执行顺序
    org.springframework.security.web.access.ExceptionTranslationFilter: trace #异常处理